# This is a basic workflow that is dev triggered

name: auto deploy to EC2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:  
  push:
    branches:
      - main  # main分支push时自动执行工作流
    paths:
      - './week5/social_media/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # 下载源码
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 安装依赖
    - name: Install Dependencies
      working-directory: ./week5/social_media
      run: npm install

    # 打包正式环境
    - name: Build
      working-directory: ./week5/social_media
      run: npm run build

    - name: Create target directory and setup web server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SOCIAL_MEDIA_HOST }}
        username: ${{ secrets.SOCIAL_MEDIA_USER }}
        key: ${{ secrets.SOCIAL_MEDIA_KEY }}
        # port: ${{ secrets.TEST1_PORT }}
        script: |
          # Create directory in user's home directory
          mkdir -p ~/yuxian-social-media
          chmod 755 ~/yuxian-social-media
          
          # Install nginx if not already installed
          if ! command -v nginx &> /dev/null; then
            sudo yum update -y
            sudo yum install -y nginx
          fi
          
          # Create nginx configuration for the app
          sudo tee /etc/nginx/conf.d/yuxian-social-media.conf > /dev/null <<EOF
          server {
              listen 80;
              server_name _;
              root /home/${{ secrets.SOCIAL_MEDIA_USER }}/yuxian-social-media;
              index index.html;
              
              location / {
                  try_files \$uri \$uri/ /index.html;
              }
          }
          EOF
          
          # Start nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v5.0.3
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SOCIAL_MEDIA_KEY }}
        REMOTE_HOST: ${{ secrets.SOCIAL_MEDIA_HOST }}
        REMOTE_USER: ${{ secrets.SOCIAL_MEDIA_USER }}
        # REMOTE_PORT: ${{ secrets.SOCIAL_MEDIA_PORT }}
        ARGS: "-avzL"
        SOURCE: "week5/social_media/dist/"
        TARGET: "~/yuxian-social-media"
        SCRIPT_AFTER: |
          # Reload nginx to serve the new files
          sudo systemctl reload nginx
          echo "Deployment completed successfully!"
